package com.minecraftmoba.plugin;
import org.bukkit.Bukkit;import org.bukkit.Location;import org.bukkit.Material;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDamageEvent;import org.bukkit.event.player.PlayerQuitEvent;import org.bukkit.scheduler.BukkitRunnable;import org.bukkit.util.Vector;import java.util.*;
/** Lightfooted runtime; numeric values are provisional calibration. */
public final class LightfootedMechanics implements Listener{
 public enum Species{WOLF,FOX,CAT_OCELOT} public record Bonus(int wolves,int foxes,int cats){} public record Provisional(double lungeDistance,double lungeDamage,int lungeTicks,double boundSpeed,int bounds,int boundTicks,double animalRadius,double damageRadius,double wolfReduction,double foxSpeed,double catFallReduction){}
 private final MobaPlugin plugin;private final Provisional v;private final Map<UUID,Bound> bounding=new HashMap<>();private final Map<UUID,Set<UUID>> hits=new HashMap<>();private final Map<UUID,Integer> windups=new HashMap<>();private final Set<UUID> classDamage=new HashSet<>();
 public LightfootedMechanics(MobaPlugin p){plugin=p;var c=p.getConfig().getConfigurationSection("abilities.lightfooted");v=new Provisional(c.getDouble("lungeDistance"),c.getDouble("lungeDamage"),c.getInt("lungeTicks"),c.getDouble("boundSpeed"),c.getInt("bounds"),c.getInt("boundTicks"),c.getDouble("animalRadius"),c.getDouble("damageRadius"),c.getDouble("wolfDamageReduction"),c.getDouble("foxSpeedBonus"),c.getDouble("catFallReduction"));}
 public Provisional values(){return v;}public boolean isLightfooted(Player p){return plugin.enrolled(p)&&"lightfooted".equals(plugin.data(p).classId);}public boolean isBounding(Player p){return bounding.containsKey(p.getUniqueId());}
 public static Species species(Entity e){return switch(e.getType()){case WOLF->Species.WOLF;case FOX->Species.FOX;case CAT,OCELOT->Species.CAT_OCELOT;default->null;};}
 public Bonus nearbyBonus(Player p){int w=0,f=0,c=0;for(Entity e:p.getNearbyEntities(v.animalRadius(),v.animalRadius(),v.animalRadius()))switch(species(e)){case WOLF->w++;case FOX->f++;case CAT_OCELOT->c++;default->{} }return new Bonus(w,f,c);}
 public boolean friendly(Entity a,Entity b){if(!(a instanceof Player pa)||!(b instanceof Player pb))return false;var s=Bukkit.getScoreboardManager().getMainScoreboard();var t=s.getEntryTeam(pa.getName());return t!=null&&t.equals(s.getEntryTeam(pb.getName()));}
 public void lunge(Player p){if(!isLightfooted(p)||isBounding(p)||windups.containsKey(p.getUniqueId()))return;String branch=plugin.getConfig().getString("abilities.lightfooted.branch","base");if("stalking_pounce".equals(branch)){windups.put(p.getUniqueId(),1);new BukkitRunnable(){public void run(){windups.remove(p.getUniqueId());if(p.isOnline()&&!p.isDead())startLunge(p, v.lungeDistance()*1.35);}}.runTaskLater(plugin,plugin.getConfig().getLong("abilities.lightfooted.pounceWindupTicks",5));return;}startLunge(p,"swarming_bite".equals(branch)?v.lungeDistance()*0.8:v.lungeDistance());}
 private void startLunge(Player p,double distance){Vector heading=p.getLocation().getDirection().normalize();if(heading.lengthSquared()==0)heading=new Vector(0,0,1);final Vector d=heading;hits.put(p.getUniqueId(),new HashSet<>());new BukkitRunnable(){int n;Location prev=p.getLocation().clone();public void run(){if(!p.isOnline()||p.isDead()||n++>=v.lungeTicks()){hits.remove(p.getUniqueId());cancel();return;}Location next=prev.clone().add(d.clone().multiply(distance/v.lungeTicks()));p.teleport(next);sweep(prev,next,p);prev=next;}}.runTaskTimer(plugin,0,1);}
 public boolean isClassDamage(Player p){return classDamage.contains(p.getUniqueId());}
 private void sweep(Location a,Location b,Player source){Vector d=b.toVector().subtract(a.toVector());int steps=Math.max(1,(int)Math.ceil(d.length()/0.25));var seen=hits.get(source.getUniqueId());for(int i=0;i<=steps;i++){Location q=a.clone().add(d.clone().multiply((double)i/steps));for(Entity e:q.getWorld().getNearbyEntities(q,v.damageRadius(),v.damageRadius(),v.damageRadius()))if(e instanceof LivingEntity t&&!t.equals(source)&&!t.isDead()&&!friendly(source,t)&&seen.add(t.getUniqueId())){classDamage.add(source.getUniqueId());try{t.damage(v.lungeDamage(),source);}finally{classDamage.remove(source.getUniqueId());}if(t instanceof Player target&&"thieving_swipe".equals(plugin.getConfig().getString("abilities.lightfooted.branch")))disableMainhand(target);}}}
 private void disableMainhand(Player target){Material m=target.getInventory().getItemInMainHand().getType();if(m!=Material.AIR)target.setCooldown(m,Math.min(plugin.getConfig().getInt("abilities.lightfooted.swipeDisableTicks",40)+nearbyBonus(target).foxes()*10,plugin.getConfig().getInt("abilities.lightfooted.swipeDisableCapTicks",100)));}
 public void beginBounding(Player p){if(!isLightfooted(p)||isBounding(p))return;bounding.put(p.getUniqueId(),new Bound(v.bounds(),null,false));launch(p);}
 private boolean terrain(Player p,String family){var b=p.getLocation().getBlock().getType().name();return switch(family){case "snow"->b.contains("SNOW");case "leaves"->b.endsWith("LEAVES");case "dirt"->b.contains("DIRT")||b.equals("GRASS_BLOCK")||b.equals("PODZOL")||b.equals("MYCELIUM");default->false;};}
 private void launch(Player p){Bound s=bounding.get(p.getUniqueId());if(s==null||s.remaining==0){bounding.remove(p.getUniqueId());return;}boolean bonus=s.bonus;s.bonus=false;if("drift_to_drift".equals(plugin.getConfig().getString("abilities.lightfooted.branch"))&&terrain(p,"snow"))p.setInvisible(true);Vector d=(s.heading==null?p.getLocation().getDirection():s.heading).normalize();s.heading=d;s.remaining--;double speed=v.boundSpeed(),height=0;if("branch_to_branch".equals(plugin.getConfig().getString("abilities.lightfooted.branch"))&&terrain(p,"leaves")){speed*=1.35;height=.35;}p.setVelocity(d.clone().multiply(speed).setY(d.getY()*speed+height));if("drift_to_drift".equals(plugin.getConfig().getString("abilities.lightfooted.branch")))p.setInvisible(false);for(Entity e:p.getNearbyEntities(v.animalRadius(),v.animalRadius(),v.animalRadius()))if(species(e)!=null)e.setVelocity(d.clone().multiply(speed));if("track_to_track".equals(plugin.getConfig().getString("abilities.lightfooted.branch"))&&!bonus&&terrain(p,"dirt")){s.remaining++;s.bonus=true;}Bukkit.getScheduler().runTaskLater(plugin,()->{if(isBounding(p)){s.heading=null;launch(p);}},v.boundTicks());}
 public boolean attackAllowed(Player p){return !isBounding(p);}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true)public void damage(EntityDamageEvent e){if(e.getEntity() instanceof Player p&&isLightfooted(p)){var b=nearbyBonus(p);e.setDamage(e.getDamage()*Math.max(0,1-b.wolves()*v.wolfReduction()));if(e.getCause()==EntityDamageEvent.DamageCause.FALL)e.setDamage(e.getDamage()*Math.max(0,1-b.cats()*v.catFallReduction()));}}
 public void luckyFoot(Player p){if(!isLightfooted(p))return;Location target=p.getTargetBlockExact(24)==null?p.getLocation().add(p.getLocation().getDirection().multiply(12)):p.getTargetBlockExact(24).getLocation();List<LivingEntity> animals=new ArrayList<>();for(Entity e:p.getNearbyEntities(v.animalRadius(),v.animalRadius(),v.animalRadius()))if(e instanceof Animals a&&species(e)!=null)animals.add(a);for(LivingEntity a:animals){a.setInvulnerable(true);a.setVelocity(target.toVector().subtract(a.getLocation().toVector()).normalize().multiply(2.2));}Bukkit.getScheduler().runTaskLater(plugin,()->{for(LivingEntity a:animals){a.setInvulnerable(false);a.teleport(target.clone().add((Math.random()-.5)*2,0,(Math.random()-.5)*2));}p.teleport(target);for(Entity e:target.getWorld().getNearbyEntities(target,2,2,2))if(e instanceof LivingEntity t&&!t.equals(p)&&!animals.contains(t))t.damage(4,p);for(LivingEntity a:animals)if(a.isValid())for(Entity e:a.getNearbyEntities(2,2,2))if(e instanceof LivingEntity t&&!animals.contains(t))t.damage(2,p);},v.boundTicks());}
 @EventHandler public void quit(PlayerQuitEvent e){clear(e.getPlayer());}public void clear(Player p){bounding.remove(p.getUniqueId());hits.remove(p.getUniqueId());windups.remove(p.getUniqueId());p.setInvisible(false);}private static final class Bound{int remaining;Vector heading;boolean bonus;Bound(int r,Vector h,boolean b){remaining=r;heading=h;bonus=b;}}
}
