package com.minecraftmoba.plugin;
import org.bukkit.Bukkit;import org.bukkit.Location;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDamageEvent;import org.bukkit.event.player.PlayerQuitEvent;import org.bukkit.scheduler.BukkitRunnable;import org.bukkit.util.Vector;import java.util.*;
/** Lightfooted runtime; numeric values are provisional calibration. */
public final class LightfootedMechanics implements Listener{
 public enum Species{WOLF,FOX,CAT_OCELOT} public record Bonus(int wolves,int foxes,int cats){} public record Provisional(double lungeDistance,double lungeDamage,int lungeTicks,double boundSpeed,int bounds,int boundTicks,double animalRadius,double damageRadius,double wolfReduction,double foxSpeed,double catFallReduction){}
 private final MobaPlugin plugin;private final Provisional v;private final Map<UUID,Bound> bounding=new HashMap<>();private final Map<UUID,Set<UUID>> hits=new HashMap<>();
 public LightfootedMechanics(MobaPlugin p){plugin=p;var c=p.getConfig().getConfigurationSection("abilities.lightfooted");v=new Provisional(c.getDouble("lungeDistance"),c.getDouble("lungeDamage"),c.getInt("lungeTicks"),c.getDouble("boundSpeed"),c.getInt("bounds"),c.getInt("boundTicks"),c.getDouble("animalRadius"),c.getDouble("damageRadius"),c.getDouble("wolfDamageReduction"),c.getDouble("foxSpeedBonus"),c.getDouble("catFallReduction"));}
 public Provisional values(){return v;}public boolean isLightfooted(Player p){return plugin.enrolled(p)&&"lightfooted".equals(plugin.data(p).classId);}public boolean isBounding(Player p){return bounding.containsKey(p.getUniqueId());}
 public static Species species(Entity e){return switch(e.getType()){case WOLF->Species.WOLF;case FOX->Species.FOX;case CAT,OCELOT->Species.CAT_OCELOT;default->null;};}
 public Bonus nearbyBonus(Player p){int w=0,f=0,c=0;for(Entity e:p.getNearbyEntities(v.animalRadius(),v.animalRadius(),v.animalRadius()))switch(species(e)){case WOLF->w++;case FOX->f++;case CAT_OCELOT->c++;default->{} }return new Bonus(w,f,c);}
 public boolean friendly(Entity a,Entity b){if(!(a instanceof Player pa)||!(b instanceof Player pb))return false;var s=Bukkit.getScoreboardManager().getMainScoreboard();var t=s.getEntryTeam(pa.getName());return t!=null&&t.equals(s.getEntryTeam(pb.getName()));}
 public void lunge(Player p){if(!isLightfooted(p)||isBounding(p))return;Vector heading=p.getLocation().getDirection().normalize();if(heading.lengthSquared()==0)heading=new Vector(0,0,1);final Vector d=heading;hits.put(p.getUniqueId(),new HashSet<>());new BukkitRunnable(){int n;Location prev=p.getLocation().clone();public void run(){if(!p.isOnline()||p.isDead()||n++>=v.lungeTicks()){hits.remove(p.getUniqueId());cancel();return;}Location next=prev.clone().add(d.clone().multiply(v.lungeDistance()/v.lungeTicks()));p.teleport(next);sweep(prev,next,p);prev=next;}}.runTaskTimer(plugin,0,1);}
 private void sweep(Location a,Location b,Player source){Vector d=b.toVector().subtract(a.toVector());int steps=Math.max(1,(int)Math.ceil(d.length()/0.25));var seen=hits.get(source.getUniqueId());for(int i=0;i<=steps;i++){Location q=a.clone().add(d.clone().multiply((double)i/steps));for(Entity e:q.getWorld().getNearbyEntities(q,v.damageRadius(),v.damageRadius(),v.damageRadius()))if(e instanceof LivingEntity t&&!t.equals(source)&&!t.isDead()&&!friendly(source,t)&&seen.add(t.getUniqueId()))t.damage(v.lungeDamage(),source);}}
 public void beginBounding(Player p){if(!isLightfooted(p)||isBounding(p))return;bounding.put(p.getUniqueId(),new Bound(v.bounds(),null));launch(p);}private void launch(Player p){Bound s=bounding.get(p.getUniqueId());if(s==null||s.remaining==0){bounding.remove(p.getUniqueId());return;}Vector d=(s.heading==null?p.getLocation().getDirection():s.heading).normalize();s.heading=d;s.remaining--;p.setVelocity(d.clone().multiply(v.boundSpeed()));for(Entity e:p.getNearbyEntities(v.animalRadius(),v.animalRadius(),v.animalRadius()))if(species(e)!=null)e.setVelocity(d.clone().multiply(v.boundSpeed()));Bukkit.getScheduler().runTaskLater(plugin,()->{if(isBounding(p)){s.heading=null;launch(p);}},v.boundTicks());}
 public boolean attackAllowed(Player p){return !isBounding(p);}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true)public void damage(EntityDamageEvent e){if(e.getEntity() instanceof Player p&&isLightfooted(p)){var b=nearbyBonus(p);e.setDamage(e.getDamage()*Math.max(0,1-b.wolves()*v.wolfReduction()));if(e.getCause()==EntityDamageEvent.DamageCause.FALL)e.setDamage(e.getDamage()*Math.max(0,1-b.cats()*v.catFallReduction()));}}
 @EventHandler public void quit(PlayerQuitEvent e){bounding.remove(e.getPlayer().getUniqueId());hits.remove(e.getPlayer().getUniqueId());}private static final class Bound{int remaining;Vector heading;Bound(int r,Vector h){remaining=r;heading=h;}}
}
