"""Turn a locally generated world into a MapCandidate the compiler can read.

The existing acquisition path (`vanilla_search.acquire.generate_world`) verifies
the official Mojang server jar by SHA-1 before it will generate anything, which
is a provenance guarantee worth keeping. That jar is not available here, so this
module takes a world generated by a server the caller names, and records WHICH
server produced it instead of claiming the official one.

That distinction is the whole point of the module. Terrain generation is vanilla
in both cases, but a candidate that says "official Mojang server, SHA-1 verified"
when it means "whatever jar was lying around" is a false provenance claim, and
the screening work downstream is only as trustworthy as that claim. So
`worldgen_truth.verified` is False here, and it says why.
"""
from __future__ import annotations

import hashlib
import json
import time
from pathlib import Path

from successor.grid import rle
from vanilla_search import DATA_VERSION, GENERATOR, SERVER_SHA1, VERSION
from vanilla_search.evaluate import evaluate_region
from vanilla_search.fit import enrich
from vanilla_search.extract import extract_region
from vanilla_search.pipeline import CHUNK_BOUNDS, _public


def harvest(world: Path, seed: int, server_jar: Path | None = None,
            chunk_bounds=CHUNK_BOUNDS) -> dict:
    started = time.perf_counter()
    extracted = extract_region(world, chunk_bounds)
    candidate = evaluate_region(extracted)
    # evaluate_region emits only the forest/buildable/highland masks. The
    # canopy and open-ground masks -- which Task A's Terrain requires, and
    # without which it raises KeyError on `canopy_mask_rle` -- come from the
    # stage-C enrichment. The screened finalists carry them because they went
    # through this step; a freshly harvested world has to as well.
    enrich(candidate)
    sha = (hashlib.sha1(Path(server_jar).read_bytes()).hexdigest()
           if server_jar and Path(server_jar).exists() else None)
    candidate.update({
        'schema_version': 1,
        'generator': GENERATOR,
        'minecraft_java_version': VERSION,
        'data_version': DATA_VERSION,
        'worldgen_truth': {
            'source': 'locally generated world',
            'server_jar_sha1': sha,
            'official_server_jar_sha1': SERVER_SHA1,
            'verified': sha == SERVER_SHA1,
            'note': 'terrain generation is vanilla, but this candidate does NOT '
                    'carry the official-jar provenance guarantee unless verified '
                    'is true; do not treat it as a screened finalist',
            'terrain_modified': False,
        },
        'seed': seed,
        'region': {'chunk_bounds': list(chunk_bounds),
                   'block_bounds': [chunk_bounds[0] * 16, chunk_bounds[1] * 16 + 15,
                                    chunk_bounds[2] * 16, chunk_bounds[3] * 16 + 15]},
        'actual_structures': extracted['structures'],
        'actual_block_volume_presence': extracted['block_volume_presence'],
        'data_completeness': {'full_chunks': extracted['full_chunks'],
                              'expected_chunks': extracted['expected_chunks']},
        'timing': {'harvest_seconds': round(time.perf_counter() - started, 2)},
        'local_world_directory': str(Path(world).resolve()),
    })
    return _public(candidate)


def main(argv=None):
    import argparse
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('world', type=Path)
    p.add_argument('seed', type=int)
    p.add_argument('--server-jar', type=Path)
    p.add_argument('--out', type=Path, required=True)
    a = p.parse_args(argv)
    candidate = harvest(a.world, a.seed, a.server_jar)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(json.dumps(candidate, indent=1))
    print(f"seed={candidate['seed']} score={candidate.get('score')} "
          f"warnings={candidate.get('experimental_screen', {}).get('warnings')} "
          f"verified_provenance={candidate['worldgen_truth']['verified']}")
    return candidate


if __name__ == '__main__':
    main()
