"""Measure the current objective forms from Minecraft's own structure data.

The spec is explicit that retained dimensions "should be measured from the
selected form, not guessed". Two of the three forms can be measured exactly,
because Minecraft ships them as structure NBT inside the client jar:

  PILLAGER OUTPOST  data/minecraft/structure/pillager_outpost/watchtower.nbt
                    -- the watchtower alone. The cages, tents, log piles,
                    targets and plates are SEPARATE feature_*.nbt files, which
                    is why "watchtower only" is a clean cut rather than a
                    judgement call: vanilla already separates them.

  NETHER BASTION    data/minecraft/structure/bastion/bridge/*
                    -- the Bridge Bastion. `starting_pieces/entrance*` and
                    `ramparts/rampart_*` are the central body and rampart;
                    `bridge_pieces/bridge.nbt` is the long projecting bridge
                    the spec removes, and `legs/*` are its supports.

The third cannot, and saying so precisely matters more than producing a number:

  END SPIKE         generated by code (SpikeFeature), not by a structure file.
                    Nothing in the jar's data can be measured for it. Its
                    parameters are DERIVED, flagged as such, and carry a lower
                    confidence than a measured form.

`measure` reports real block counts and real extents from the real files. Where
a fact cannot be established it is absent, not estimated.
"""
from __future__ import annotations

import io
import json
import zipfile
from pathlib import Path

from serialization.nbt import loads, plain

# Where a normal Minecraft install keeps its jars. Overridable; the point is
# that the asset source is the game, not a hand-copied approximation.
DEFAULT_JAR = (Path.home() / 'Library' / 'Application Support' / 'minecraft'
               / 'versions' / '1.21.11' / '1.21.11.jar')

WATCHTOWER = 'data/minecraft/structure/pillager_outpost/watchtower.nbt'

# The Outpost pieces vanilla attaches around the watchtower. Named so the
# exclusion is checkable rather than asserted.
OUTPOST_PERIPHERAL = (
    'feature_cage1', 'feature_cage2', 'feature_cage_with_allays', 'feature_logs',
    'feature_plate', 'feature_targets', 'feature_tent1', 'feature_tent2',
    'base_plate',
)

# The retained Bridge Bastion: central body and rampart. Vanilla assembles a
# bastion from many pieces; these are the ones the current form keeps.
BASTION_RETAINED = (
    'data/minecraft/structure/bastion/bridge/starting_pieces/entrance.nbt',
    'data/minecraft/structure/bastion/bridge/starting_pieces/entrance_base.nbt',
    'data/minecraft/structure/bastion/bridge/ramparts/rampart_0.nbt',
    'data/minecraft/structure/bastion/bridge/ramparts/rampart_1.nbt',
)

# Explicitly dropped: the long projecting bridge and the legs that carry it.
BASTION_REMOVED = (
    'data/minecraft/structure/bastion/bridge/bridge_pieces/bridge.nbt',
    'data/minecraft/structure/bastion/bridge/legs/leg_0.nbt',
    'data/minecraft/structure/bastion/bridge/legs/leg_1.nbt',
)


def read_structure(jar: Path, entry: str) -> dict:
    """Read one structure NBT out of the jar. Structure files are gzipped."""
    import gzip
    with zipfile.ZipFile(jar) as z:
        raw = z.read(entry)
    if raw[:2] == b'\x1f\x8b':
        raw = gzip.decompress(raw)
    return plain(loads(raw)[1])


def _palette_names(doc) -> list[str]:
    palette = doc.get('palette') or []
    return [str(p.get('Name', '')) for p in palette]


def measure_structure(doc) -> dict:
    """Real extents and real solid-block counts, from the file's own blocks."""
    size = [int(v) for v in doc['size']]
    names = _palette_names(doc)
    air = {i for i, n in enumerate(names)
           if n in ('minecraft:air', 'minecraft:cave_air', 'minecraft:void_air',
                    'minecraft:structure_void')}
    blocks = doc.get('blocks') or []
    solid = [b for b in blocks if int(b.get('state', -1)) not in air]
    if not solid:
        return {'size_xyz': size, 'solid_blocks': 0}
    xs = [int(b['pos'][0]) for b in solid]
    ys = [int(b['pos'][1]) for b in solid]
    zs = [int(b['pos'][2]) for b in solid]
    footprint = {(int(b['pos'][0]), int(b['pos'][2])) for b in solid}
    # Ground contact: the lowest occupied layer, which is what a socket's
    # terrain actually has to support.
    floor = min(ys)
    contact = {(int(b['pos'][0]), int(b['pos'][2])) for b in solid
               if int(b['pos'][1]) == floor}
    return {
        'size_xyz': size,
        'solid_blocks': len(solid),
        'occupied_extent_xyz': [max(xs) - min(xs) + 1,
                                max(ys) - min(ys) + 1,
                                max(zs) - min(zs) + 1],
        'footprint_columns': len(footprint),
        'ground_contact_columns': len(contact),
        'height': max(ys) - min(ys) + 1,
        'palette_size': len(names),
    }


def _combine(parts: dict) -> dict:
    """A multi-piece form's contract: the span it needs, and how solid it is."""
    spans_x = max(p['size_xyz'][0] for p in parts.values())
    spans_z = max(p['size_xyz'][2] for p in parts.values())
    return {
        'pieces': {k: v for k, v in parts.items()},
        'span_x': spans_x,
        'span_z': spans_z,
        'height': max(p['height'] for p in parts.values()),
        'solid_blocks': sum(p['solid_blocks'] for p in parts.values()),
        'ground_contact_columns': max(p['ground_contact_columns'] for p in parts.values()),
    }


def measure(jar: Path = DEFAULT_JAR) -> dict:
    """Measure what can be measured; say plainly what cannot."""
    if not jar.exists():
        return {'available': False,
                'why': f'no Minecraft jar at {jar}; objective forms cannot be measured '
                       f'and must not be guessed'}

    with zipfile.ZipFile(jar) as z:
        present = set(z.namelist())

    out = {'available': True, 'source_jar': str(jar), 'forms': {}}

    # --- Pillager Outpost: the watchtower alone ---------------------------
    tower = measure_structure(read_structure(jar, WATCHTOWER))
    peripheral = [n for n in OUTPOST_PERIPHERAL
                  if f'data/minecraft/structure/pillager_outpost/{n}.nbt' in present]
    out['forms']['pillager_outpost'] = {
        'evidence': 'measured',
        'source': WATCHTOWER,
        'form': 'watchtower only',
        # Vanilla ships the peripheral pieces as separate files, so excluding
        # them is a file-level cut, not an interpretation of one mesh.
        'excluded_vanilla_pieces': peripheral,
        **tower,
        'span_samples': max(tower['size_xyz'][0], tower['size_xyz'][2]),
        'interior_navigation': True,
        'vertical_clearance': tower['height'],
    }

    # --- Nether Bastion: bridge rampart / central body ---------------------
    retained = {}
    for entry in BASTION_RETAINED:
        if entry in present:
            retained[entry.rsplit('/', 1)[-1]] = measure_structure(read_structure(jar, entry))
    if retained:
        body = _combine(retained)
        out['forms']['nether_bastion'] = {
            'evidence': 'measured',
            'source': [e for e in BASTION_RETAINED if e in present],
            'form': 'bridge bastion rampart / central body, projecting bridge removed',
            'removed_vanilla_pieces': [e for e in BASTION_REMOVED if e in present],
            **body,
            'span_samples': max(body['span_x'], body['span_z']),
            'interior_navigation': True,
            'multilevel': True,
            'vertical_clearance': body['height'],
        }
    else:
        out['forms']['nether_bastion'] = {
            'evidence': 'unavailable',
            'why': 'no bridge bastion pieces in this jar',
        }

    # --- End Spike: not a structure file ----------------------------------
    # There is nothing here to measure. Vanilla builds the arena spikes in
    # code, so the jar's data contains no file for them at any path. Recording
    # a plausible pillar here would be exactly the guess the spec forbids, and
    # it would be indistinguishable from the two measured forms above.
    out['forms']['end_spike'] = {
        'evidence': 'not_measurable_from_data',
        'why': 'the Ender Dragon arena spikes are generated by code (SpikeFeature), '
               'not shipped as structure NBT. No file in the jar describes them, so '
               'no dimension here is measured.',
        'needs': ['pillar radius', 'pillar height', 'crystal placement',
                  'cage geometry where applicable'],
        'how_to_establish': 'generate a vanilla End dimension and measure the spikes '
                            'from the produced region files, the same way a Homebase '
                            'socket is measured from terrain',
        'span_samples': None,
        'interior_navigation': False,
    }
    return out


def main(argv=None):
    import argparse
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--jar', type=Path, default=DEFAULT_JAR)
    p.add_argument('--out', type=Path)
    a = p.parse_args(argv)
    result = measure(a.jar)
    text = json.dumps(result, indent=1)
    if a.out:
        a.out.parent.mkdir(parents=True, exist_ok=True)
        a.out.write_text(text)
    print(text)
    return result


if __name__ == '__main__':
    main()
